-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_linear_ap_fixed_15_5_5_3_0_ap_fixed_16_6_5_3_0_linear_config11_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (14 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_linear_ap_fixed_15_5_5_3_0_ap_fixed_16_6_5_3_0_linear_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln32_fu_36_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln32_35_fu_40_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln32_36_fu_44_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= sext_ln32_fu_36_p1;
    ap_return_1 <= sext_ln32_35_fu_40_p1;
    ap_return_2 <= sext_ln32_36_fu_44_p1;
        sext_ln32_35_fu_40_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val),16));

        sext_ln32_36_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val),16));

        sext_ln32_fu_36_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val),16));

end behav;
