Backend: Vitis
ClockPeriod: 25
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        scale: fixed<16,6>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    batch_normalization_1:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        scale: fixed<16,6>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense1:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense1_linear:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense2:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense2_linear:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense_output:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense_output_linear:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    q_activation:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    q_activation_1:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    y_timed_input:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<10,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
KerasModel: !keras_model 'alex_model//keras_model.h5'
OutputDir: alex_model/
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: eC215dE9
Version: 1.0.0
XilinxPart: xcku040-ffva1156-2-e
