Backend: Vitis
ClockPeriod: 25
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    batch_normalization_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    dense1:
      Precision:
        bias: fixed<10,1>
        result: fixed<16,6>
        weight: fixed<10,1>
      Trace: false
    dense1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense2:
      Precision:
        bias: fixed<10,1>
        result: fixed<16,6>
        weight: fixed<10,1>
      Trace: false
    dense2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_output:
      Precision:
        bias: fixed<10,1>
        result: fixed<16,6>
        weight: fixed<10,1>
      Trace: false
    dense_output_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    q_activation:
      Precision:
        result: ufixed<10,0,RND_CONV,SAT>
      Trace: false
    q_activation_1:
      Precision:
        result: ufixed<10,0,RND_CONV,SAT>
      Trace: false
    y_timed_input:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
KerasModel: !keras_model 'alex_model//keras_model.h5'
OutputDir: alex_model/
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: aFC8CF3d
Version: 1.0.0
XilinxPart: xcku040-ffva1156-2-e
