Backend: Vitis
ClockPeriod: 25
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        scale: fixed<16,6>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense1:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    dense1_linear:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    flatten_input:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    latent_space:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    latent_space_linear:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    q_activation:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
    y_profile_input:
      Precision:
        bias: ap_fixed<10,2>
        result: ap_fixed<15,2>
        weight: ap_fixed<10,2>
      Strategy: Latency
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
KerasModel: !keras_model 'alex_model//keras_model.h5'
OutputDir: alex_model/
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: 6ba3E8B3
Version: 1.0.0
XilinxPart: xcku040-ffva1156-2-e
