// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer8_out_dout,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_empty_n,
        layer8_out_read,
        layer9_out_din,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_full_n,
        layer9_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [95:0] layer8_out_dout;
input  [5:0] layer8_out_num_data_valid;
input  [5:0] layer8_out_fifo_cap;
input   layer8_out_empty_n;
output   layer8_out_read;
output  [63:0] layer9_out_din;
input  [3:0] layer9_out_num_data_valid;
input  [3:0] layer9_out_fifo_cap;
input   layer9_out_full_n;
output   layer9_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer8_out_read;
reg layer9_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln55_reg_946;
reg   [0:0] icmp_ln55_reg_946_pp0_iter1_reg;
reg   [0:0] and_ln55_1_reg_968;
reg    ap_predicate_op144_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_148_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [23:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
reg   [23:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [23:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [23:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
reg   [23:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_3;
reg   [23:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_2;
reg   [23:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_1;
reg   [23:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0;
wire   [23:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0;
reg    layer8_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
reg   [0:0] icmp_ln109_reg_942;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_164_p2;
wire   [0:0] icmp_ln55_2_fu_178_p2;
reg   [0:0] icmp_ln55_2_reg_950;
wire   [0:0] icmp_ln55_3_fu_184_p2;
reg   [0:0] icmp_ln55_3_reg_955;
wire   [0:0] icmp_ln76_fu_196_p2;
reg   [0:0] icmp_ln76_reg_960;
wire   [0:0] icmp_ln80_fu_250_p2;
reg   [0:0] icmp_ln80_reg_964;
wire   [0:0] and_ln55_1_fu_441_p2;
wire   [15:0] res_pack_4_fu_647_p3;
reg   [15:0] res_pack_4_reg_972;
wire   [15:0] res_pack_5_fu_727_p3;
reg   [15:0] res_pack_5_reg_977;
wire   [15:0] res_pack_6_fu_807_p3;
reg   [15:0] res_pack_6_reg_982;
wire   [15:0] res_pack_fu_887_p3;
reg   [15:0] res_pack_reg_987;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_133_p4;
wire   [31:0] add_ln86_fu_913_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_129;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_129;
wire   [31:0] add_ln80_fu_244_p2;
wire   [31:0] add_ln76_fu_190_p2;
wire   [31:0] add_ln91_fu_216_p2;
wire   [23:0] trunc_ln115_fu_273_p1;
wire   [23:0] trunc_ln115_5_fu_297_p4;
wire   [23:0] trunc_ln115_2_fu_277_p4;
wire   [23:0] trunc_ln115_3_fu_287_p4;
reg   [4:0] indvar_flatten_fu_112;
wire   [4:0] add_ln109_fu_154_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] select_ln91_fu_208_p3;
wire   [0:0] and_ln55_fu_437_p2;
wire   [0:0] icmp_ln55_1_fu_431_p2;
wire   [29:0] pool_window_fu_447_p3;
wire   [29:0] pool_window_1_fu_455_p3;
wire   [0:0] icmp_ln65_fu_575_p2;
wire   [0:0] xor_ln65_fu_581_p2;
wire   [29:0] pool_window_2_fu_463_p3;
wire   [29:0] pool_window_3_fu_471_p3;
wire   [0:0] icmp_ln65_1_fu_595_p2;
wire   [0:0] xor_ln65_1_fu_601_p2;
wire   [29:0] select_ln65_fu_587_p3;
wire   [29:0] select_ln65_1_fu_607_p3;
wire   [0:0] icmp_ln65_2_fu_615_p2;
wire   [0:0] xor_ln65_2_fu_621_p2;
wire   [15:0] tmp_s_fu_627_p4;
wire   [15:0] tmp_1_fu_637_p4;
wire   [29:0] pool_window_4_fu_479_p3;
wire   [29:0] pool_window_5_fu_487_p3;
wire   [0:0] icmp_ln65_3_fu_655_p2;
wire   [0:0] xor_ln65_3_fu_661_p2;
wire   [29:0] pool_window_6_fu_495_p3;
wire   [29:0] pool_window_7_fu_503_p3;
wire   [0:0] icmp_ln65_4_fu_675_p2;
wire   [0:0] xor_ln65_4_fu_681_p2;
wire   [29:0] select_ln65_3_fu_667_p3;
wire   [29:0] select_ln65_4_fu_687_p3;
wire   [0:0] icmp_ln65_5_fu_695_p2;
wire   [0:0] xor_ln65_5_fu_701_p2;
wire   [15:0] tmp_2_fu_707_p4;
wire   [15:0] tmp_3_fu_717_p4;
wire   [29:0] pool_window_8_fu_511_p3;
wire   [29:0] pool_window_9_fu_519_p3;
wire   [0:0] icmp_ln65_6_fu_735_p2;
wire   [0:0] xor_ln65_6_fu_741_p2;
wire   [29:0] pool_window_15_fu_527_p3;
wire   [29:0] pool_window_10_fu_535_p3;
wire   [0:0] icmp_ln65_7_fu_755_p2;
wire   [0:0] xor_ln65_7_fu_761_p2;
wire   [29:0] select_ln65_6_fu_747_p3;
wire   [29:0] select_ln65_7_fu_767_p3;
wire   [0:0] icmp_ln65_8_fu_775_p2;
wire   [0:0] xor_ln65_8_fu_781_p2;
wire   [15:0] tmp_4_fu_787_p4;
wire   [15:0] tmp_5_fu_797_p4;
wire   [29:0] pool_window_11_fu_543_p3;
wire   [29:0] pool_window_12_fu_551_p3;
wire   [0:0] icmp_ln65_9_fu_815_p2;
wire   [0:0] xor_ln65_9_fu_821_p2;
wire   [29:0] pool_window_13_fu_559_p3;
wire   [29:0] pool_window_14_fu_567_p3;
wire   [0:0] icmp_ln65_10_fu_835_p2;
wire   [0:0] xor_ln65_10_fu_841_p2;
wire   [29:0] select_ln65_9_fu_827_p3;
wire   [29:0] select_ln65_10_fu_847_p3;
wire   [0:0] icmp_ln65_11_fu_855_p2;
wire   [0:0] xor_ln65_11_fu_861_p2;
wire   [15:0] tmp_6_fu_867_p4;
wire   [15:0] tmp_7_fu_877_p4;
wire   [0:0] icmp_ln86_fu_899_p2;
wire   [31:0] select_ln86_fu_905_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_216;
reg    ap_condition_214;
reg    ap_condition_281;
reg    ap_condition_240;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 = 24'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 24'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 24'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 = 24'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_3 = 24'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_2 = 24'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_1 = 24'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a = 24'd0;
end

myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s_void_pjbC #(
    .DataWidth( 24 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0),
    .d0(trunc_ln115_fu_273_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s_void_pjbC #(
    .DataWidth( 24 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s_void_pjbC #(
    .DataWidth( 24 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s_void_pjbC #(
    .DataWidth( 24 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd5),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_214)) begin
        if ((1'b1 == ap_condition_216)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_129 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_129 <= ap_phi_reg_pp0_iter0_storemerge_reg_129;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_214)) begin
        if ((icmp_ln109_fu_148_p2 == 1'd0)) begin
            indvar_flatten_fu_112 <= add_ln109_fu_154_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_112 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_281)) begin
        if ((icmp_ln76_fu_196_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_fu_196_p2 == 1'd0)) begin
            pX <= add_ln76_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_240)) begin
        if ((icmp_ln80_fu_250_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln80_fu_250_p2 == 1'd0)) begin
            pY <= add_ln80_fu_244_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_281)) begin
        if ((icmp_ln76_fu_196_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln76_fu_196_p2 == 1'd0)) begin
            sX <= add_ln91_fu_216_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_reg_946 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_968 <= and_ln55_1_fu_441_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln109_reg_942 <= icmp_ln109_fu_148_p2;
        icmp_ln55_reg_946_pp0_iter1_reg <= icmp_ln55_reg_946;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_fu_164_p2 == 1'd1))) begin
        icmp_ln55_2_reg_950 <= icmp_ln55_2_fu_178_p2;
        icmp_ln55_3_reg_955 <= icmp_ln55_3_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_946 <= icmp_ln55_fu_164_p2;
        icmp_ln76_reg_960 <= icmp_ln76_fu_196_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_196_p2 == 1'd1))) begin
        icmp_ln80_reg_964 <= icmp_ln80_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a <= {{layer8_out_dout[95:72]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_1 <= {{layer8_out_dout[71:48]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_2 <= {{layer8_out_dout[47:24]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_3 <= trunc_ln115_fu_273_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_fu_441_p2) & (icmp_ln55_reg_946 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_pack_4_reg_972 <= res_pack_4_fu_647_p3;
        res_pack_5_reg_977 <= res_pack_5_fu_727_p3;
        res_pack_6_reg_982 <= res_pack_6_fu_807_p3;
        res_pack_reg_987 <= res_pack_fu_887_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_reg_960 == 1'd1))) begin
        sY <= ap_phi_mux_storemerge_phi_fu_133_p4;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_148_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_964 == 1'd0) & (icmp_ln76_reg_960 == 1'd1) & (icmp_ln109_reg_942 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_133_p4 = add_ln86_fu_913_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_133_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_129;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op144_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op144_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_154_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln76_fu_190_p2 = (pX + 32'd1);

assign add_ln80_fu_244_p2 = (pY + 32'd1);

assign add_ln86_fu_913_p2 = (sY + select_ln86_fu_905_p3);

assign add_ln91_fu_216_p2 = (sX + select_ln91_fu_208_p3);

assign and_ln55_1_fu_441_p2 = (icmp_ln55_1_fu_431_p2 & and_ln55_fu_437_p2);

assign and_ln55_fu_437_p2 = (icmp_ln55_3_reg_955 & icmp_ln55_2_reg_950);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op144_write_state3 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer8_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op144_write_state3 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer8_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_predicate_op144_write_state3 == 1'b1) & (layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer8_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer8_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op144_write_state3 == 1'b1) & (layer9_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_214 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_216 = ((icmp_ln109_fu_148_p2 == 1'd0) & (icmp_ln80_fu_250_p2 == 1'd1) & (icmp_ln76_fu_196_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_240 = ((icmp_ln109_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_196_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_281 = ((icmp_ln109_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_129 = 'bx;

always @ (*) begin
    ap_predicate_op144_write_state3 = ((1'd1 == and_ln55_1_reg_968) & (icmp_ln55_reg_946_pp0_iter1_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln109_fu_148_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_431_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_178_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_184_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_164_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln65_10_fu_835_p2 = ((pool_window_13_fu_559_p3 < pool_window_14_fu_567_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_11_fu_855_p2 = ((select_ln65_9_fu_827_p3 < select_ln65_10_fu_847_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_595_p2 = ((pool_window_2_fu_463_p3 < pool_window_3_fu_471_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_615_p2 = ((select_ln65_fu_587_p3 < select_ln65_1_fu_607_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_655_p2 = ((pool_window_4_fu_479_p3 < pool_window_5_fu_487_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_675_p2 = ((pool_window_6_fu_495_p3 < pool_window_7_fu_503_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_5_fu_695_p2 = ((select_ln65_3_fu_667_p3 < select_ln65_4_fu_687_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_6_fu_735_p2 = ((pool_window_8_fu_511_p3 < pool_window_9_fu_519_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_7_fu_755_p2 = ((pool_window_15_fu_527_p3 < pool_window_10_fu_535_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_8_fu_775_p2 = ((select_ln65_6_fu_747_p3 < select_ln65_7_fu_767_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_9_fu_815_p2 = ((pool_window_11_fu_543_p3 < pool_window_12_fu_551_p3) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_575_p2 = ((pool_window_fu_447_p3 < pool_window_1_fu_455_p3) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_196_p2 = ((add_ln76_fu_190_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_250_p2 = ((add_ln80_fu_244_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_899_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign layer9_out_din = {{{{res_pack_reg_987}, {res_pack_6_reg_982}}, {res_pack_5_reg_977}}, {res_pack_4_reg_972}};

assign pool_window_10_fu_535_p3 = {{trunc_ln115_2_fu_277_p4}, {6'd0}};

assign pool_window_11_fu_543_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3}, {6'd0}};

assign pool_window_12_fu_551_p3 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0}, {6'd0}};

assign pool_window_13_fu_559_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a}, {6'd0}};

assign pool_window_14_fu_567_p3 = {{trunc_ln115_3_fu_287_p4}, {6'd0}};

assign pool_window_15_fu_527_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_1}, {6'd0}};

assign pool_window_1_fu_455_p3 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0}, {6'd0}};

assign pool_window_2_fu_463_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_3}, {6'd0}};

assign pool_window_3_fu_471_p3 = {{trunc_ln115_fu_273_p1}, {6'd0}};

assign pool_window_4_fu_479_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1}, {6'd0}};

assign pool_window_5_fu_487_p3 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0}, {6'd0}};

assign pool_window_6_fu_495_p3 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi24ELi8EL9ap_q_mode4EL9a_2}, {6'd0}};

assign pool_window_7_fu_503_p3 = {{trunc_ln115_5_fu_297_p4}, {6'd0}};

assign pool_window_8_fu_511_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel}, {6'd0}};

assign pool_window_9_fu_519_p3 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0}, {6'd0}};

assign pool_window_fu_447_p3 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2}, {6'd0}};

assign res_pack_4_fu_647_p3 = ((xor_ln65_2_fu_621_p2[0:0] == 1'b1) ? tmp_s_fu_627_p4 : tmp_1_fu_637_p4);

assign res_pack_5_fu_727_p3 = ((xor_ln65_5_fu_701_p2[0:0] == 1'b1) ? tmp_2_fu_707_p4 : tmp_3_fu_717_p4);

assign res_pack_6_fu_807_p3 = ((xor_ln65_8_fu_781_p2[0:0] == 1'b1) ? tmp_4_fu_787_p4 : tmp_5_fu_797_p4);

assign res_pack_fu_887_p3 = ((xor_ln65_11_fu_861_p2[0:0] == 1'b1) ? tmp_6_fu_867_p4 : tmp_7_fu_877_p4);

assign select_ln65_10_fu_847_p3 = ((xor_ln65_10_fu_841_p2[0:0] == 1'b1) ? pool_window_13_fu_559_p3 : pool_window_14_fu_567_p3);

assign select_ln65_1_fu_607_p3 = ((xor_ln65_1_fu_601_p2[0:0] == 1'b1) ? pool_window_2_fu_463_p3 : pool_window_3_fu_471_p3);

assign select_ln65_3_fu_667_p3 = ((xor_ln65_3_fu_661_p2[0:0] == 1'b1) ? pool_window_4_fu_479_p3 : pool_window_5_fu_487_p3);

assign select_ln65_4_fu_687_p3 = ((xor_ln65_4_fu_681_p2[0:0] == 1'b1) ? pool_window_6_fu_495_p3 : pool_window_7_fu_503_p3);

assign select_ln65_6_fu_747_p3 = ((xor_ln65_6_fu_741_p2[0:0] == 1'b1) ? pool_window_8_fu_511_p3 : pool_window_9_fu_519_p3);

assign select_ln65_7_fu_767_p3 = ((xor_ln65_7_fu_761_p2[0:0] == 1'b1) ? pool_window_15_fu_527_p3 : pool_window_10_fu_535_p3);

assign select_ln65_9_fu_827_p3 = ((xor_ln65_9_fu_821_p2[0:0] == 1'b1) ? pool_window_11_fu_543_p3 : pool_window_12_fu_551_p3);

assign select_ln65_fu_587_p3 = ((xor_ln65_fu_581_p2[0:0] == 1'b1) ? pool_window_fu_447_p3 : pool_window_1_fu_455_p3);

assign select_ln86_fu_905_p3 = ((icmp_ln86_fu_899_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_208_p3 = ((icmp_ln55_fu_164_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign start_out = real_start;

assign tmp_1_fu_637_p4 = {{select_ln65_1_fu_607_p3[27:12]}};

assign tmp_2_fu_707_p4 = {{select_ln65_3_fu_667_p3[27:12]}};

assign tmp_3_fu_717_p4 = {{select_ln65_4_fu_687_p3[27:12]}};

assign tmp_4_fu_787_p4 = {{select_ln65_6_fu_747_p3[27:12]}};

assign tmp_5_fu_797_p4 = {{select_ln65_7_fu_767_p3[27:12]}};

assign tmp_6_fu_867_p4 = {{select_ln65_9_fu_827_p3[27:12]}};

assign tmp_7_fu_877_p4 = {{select_ln65_10_fu_847_p3[27:12]}};

assign tmp_s_fu_627_p4 = {{select_ln65_fu_587_p3[27:12]}};

assign trunc_ln115_2_fu_277_p4 = {{layer8_out_dout[71:48]}};

assign trunc_ln115_3_fu_287_p4 = {{layer8_out_dout[95:72]}};

assign trunc_ln115_5_fu_297_p4 = {{layer8_out_dout[47:24]}};

assign trunc_ln115_fu_273_p1 = layer8_out_dout[23:0];

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0 = {{layer8_out_dout[71:48]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0 = {{layer8_out_dout[47:24]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0 = {{layer8_out_dout[95:72]}};

assign xor_ln65_10_fu_841_p2 = (icmp_ln65_10_fu_835_p2 ^ 1'd1);

assign xor_ln65_11_fu_861_p2 = (icmp_ln65_11_fu_855_p2 ^ 1'd1);

assign xor_ln65_1_fu_601_p2 = (icmp_ln65_1_fu_595_p2 ^ 1'd1);

assign xor_ln65_2_fu_621_p2 = (icmp_ln65_2_fu_615_p2 ^ 1'd1);

assign xor_ln65_3_fu_661_p2 = (icmp_ln65_3_fu_655_p2 ^ 1'd1);

assign xor_ln65_4_fu_681_p2 = (icmp_ln65_4_fu_675_p2 ^ 1'd1);

assign xor_ln65_5_fu_701_p2 = (icmp_ln65_5_fu_695_p2 ^ 1'd1);

assign xor_ln65_6_fu_741_p2 = (icmp_ln65_6_fu_735_p2 ^ 1'd1);

assign xor_ln65_7_fu_761_p2 = (icmp_ln65_7_fu_755_p2 ^ 1'd1);

assign xor_ln65_8_fu_781_p2 = (icmp_ln65_8_fu_775_p2 ^ 1'd1);

assign xor_ln65_9_fu_821_p2 = (icmp_ln65_9_fu_815_p2 ^ 1'd1);

assign xor_ln65_fu_581_p2 = (icmp_ln65_fu_575_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_ap_ufixed_4u_array_ap_fixed_16_6_5_3_0_4u_config9_s
