// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        in_elem_0_0_0_0_0_val,
        layer2_out_din,
        layer2_out_num_data_valid,
        layer2_out_fifo_cap,
        layer2_out_full_n,
        layer2_out_write,
        layer2_out_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] in_elem_0_0_0_0_0_val;
output  [127:0] layer2_out_din;
input  [7:0] layer2_out_num_data_valid;
input  [7:0] layer2_out_fifo_cap;
input   layer2_out_full_n;
output   layer2_out_write;
output   layer2_out_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer2_out_write;
reg layer2_out_blk_n;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_subdone;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
reg   [31:0] sX_3;
reg   [31:0] sY_3;
reg   [31:0] pY_3;
reg   [31:0] pX_3;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln289_reg_359;
reg   [0:0] and_ln289_1_reg_363;
wire   [0:0] icmp_ln289_fu_146_p2;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] and_ln289_1_fu_208_p2;
reg   [15:0] res_out_reg_367;
reg   [15:0] res_out_8_reg_372;
reg   [15:0] res_out_9_reg_377;
reg   [15:0] res_out_10_reg_382;
reg   [15:0] res_out_4_reg_387;
reg   [15:0] res_out_5_reg_392;
reg   [15:0] res_out_6_reg_397;
reg   [15:0] res_out_7_reg_402;
wire   [0:0] icmp_ln313_fu_252_p2;
reg   [0:0] icmp_ln313_reg_407;
wire   [31:0] select_ln323_fu_326_p3;
wire   [0:0] icmp_ln317_fu_302_p2;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op51_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_start;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_done;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_idle;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ready;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld;
reg    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call2;
reg    ap_block_state3_pp0_stage0_iter1_ignore_call2;
reg    ap_block_pp0_stage0_11001_ignoreCallOp5;
wire    tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_ready;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_0;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_1;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_2;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_3;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_4;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_5;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_6;
wire   [15:0] tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_7;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_81;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_81;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1;
wire   [31:0] select_ln328_fu_270_p3;
wire   [31:0] add_ln317_fu_296_p2;
wire   [31:0] add_ln313_fu_246_p2;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] tmp_3_fu_170_p4;
wire   [30:0] tmp_4_fu_186_p4;
wire   [0:0] icmp_ln289_2_fu_180_p2;
wire   [0:0] icmp_ln289_3_fu_196_p2;
wire   [0:0] and_ln289_fu_202_p2;
wire   [0:0] icmp_ln289_1_fu_164_p2;
wire   [31:0] add_ln328_fu_264_p2;
wire   [0:0] icmp_ln323_fu_314_p2;
wire   [31:0] add_ln323_fu_320_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
reg    ap_condition_199;
reg    ap_condition_264;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 = 16'd0;
#0 sX_3 = 32'd0;
#0 sY_3 = 32'd0;
#0 pY_3 = 32'd0;
#0 pX_3 = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_start),
    .ap_done(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_done),
    .ap_idle(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_idle),
    .ap_ready(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld),
    .ap_ce(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ce)
);

myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120(
    .ap_ready(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .ap_return_0(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_0),
    .ap_return_1(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_1),
    .ap_return_2(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_2),
    .ap_return_3(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_3),
    .ap_return_4(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_4),
    .ap_return_5(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_5),
    .ap_return_6(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_6),
    .ap_return_7(tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if (((icmp_ln317_fu_302_p2 == 1'd1) & (icmp_ln313_fu_252_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_81 <= 32'd0;
        end else if (((icmp_ln317_fu_302_p2 == 1'd0) & (icmp_ln313_fu_252_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_81 <= select_ln323_fu_326_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_81 <= ap_phi_reg_pp0_iter0_storemerge_reg_81;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((icmp_ln313_fu_252_p2 == 1'd1)) begin
            pX_3 <= 32'd0;
        end else if ((icmp_ln313_fu_252_p2 == 1'd0)) begin
            pX_3 <= add_ln313_fu_246_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_264)) begin
        if ((icmp_ln317_fu_302_p2 == 1'd1)) begin
            pY_3 <= 32'd0;
        end else if ((icmp_ln317_fu_302_p2 == 1'd0)) begin
            pY_3 <= add_ln317_fu_296_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_199)) begin
        if ((icmp_ln313_fu_252_p2 == 1'd1)) begin
            sX_3 <= 32'd0;
        end else if ((icmp_ln313_fu_252_p2 == 1'd0)) begin
            sX_3 <= select_ln328_fu_270_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln289_fu_146_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        and_ln289_1_reg_363 <= and_ln289_1_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln289_reg_359 <= icmp_ln289_fu_146_p2;
        icmp_ln313_reg_407 <= icmp_ln313_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln289_fu_146_p2 == 1'd1) & (1'd1 == and_ln289_1_fu_208_p2) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        res_out_10_reg_382 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_3;
        res_out_4_reg_387 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_4;
        res_out_5_reg_392 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_5;
        res_out_6_reg_397 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_6;
        res_out_7_reg_402 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_7;
        res_out_8_reg_372 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_1;
        res_out_9_reg_377 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_2;
        res_out_reg_367 <= tmp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_120_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln313_reg_407 == 1'd1))) begin
        sY_3 <= ap_phi_reg_pp0_iter1_storemerge_reg_81;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp5) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ce = 1'b1;
    end else begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_start = 1'b1;
    end else begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_92_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln289_1_reg_363) & (icmp_ln289_reg_359 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op51_write_state3 == 1'b1))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln313_fu_246_p2 = (pX_3 + 32'd1);

assign add_ln317_fu_296_p2 = (pY_3 + 32'd1);

assign add_ln323_fu_320_p2 = (sY_3 + 32'd1);

assign add_ln328_fu_264_p2 = (sX_3 + 32'd1);

assign and_ln289_1_fu_208_p2 = (icmp_ln289_1_fu_164_p2 & and_ln289_fu_202_p2);

assign and_ln289_fu_202_p2 = (icmp_ln289_3_fu_196_p2 & icmp_ln289_2_fu_180_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((layer2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op51_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((layer2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op51_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp5 = ((layer2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op51_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((layer2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op51_write_state3 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op51_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1_ignore_call2 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op51_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_199 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_264 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln313_fu_252_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_reg_81 = 'bx;

always @ (*) begin
    ap_predicate_op51_write_state3 = ((1'd1 == and_ln289_1_reg_363) & (icmp_ln289_reg_359 == 1'd1));
end

assign icmp_ln289_1_fu_164_p2 = ((sY_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln289_2_fu_180_p2 = (($signed(tmp_3_fu_170_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_3_fu_196_p2 = (($signed(tmp_4_fu_186_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_146_p2 = ((sX_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_252_p2 = ((add_ln313_fu_246_p2 == 32'd15) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_302_p2 = ((add_ln317_fu_296_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln323_fu_314_p2 = ((sY_3 == 32'd2) ? 1'b1 : 1'b0);

assign layer2_out_din = {{{{{{{{res_out_7_reg_402}, {res_out_6_reg_397}}, {res_out_5_reg_392}}, {res_out_4_reg_387}}, {res_out_10_reg_382}}, {res_out_9_reg_377}}, {res_out_8_reg_372}}, {res_out_reg_367}};

assign select_ln323_fu_326_p3 = ((icmp_ln323_fu_314_p2[0:0] == 1'b1) ? 32'd2 : add_ln323_fu_320_p2);

assign select_ln328_fu_270_p3 = ((icmp_ln289_fu_146_p2[0:0] == 1'b1) ? 32'd2 : add_ln328_fu_264_p2);

assign tmp_3_fu_170_p4 = {{pY_3[31:1]}};

assign tmp_4_fu_186_p4 = {{pX_3[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config2_s
