// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer9_out_dout,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_empty_n,
        layer9_out_read,
        y0_input_TDATA,
        y0_input_TVALID,
        y0_input_TREADY,
        layer12_out_din,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer12_out_full_n,
        layer12_out_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [207:0] layer9_out_dout;
input  [3:0] layer9_out_num_data_valid;
input  [3:0] layer9_out_fifo_cap;
input   layer9_out_empty_n;
output   layer9_out_read;
input  [15:0] y0_input_TDATA;
input   y0_input_TVALID;
output   y0_input_TREADY;
output  [1263:0] layer12_out_din;
input  [1:0] layer12_out_num_data_valid;
input  [1:0] layer12_out_fifo_cap;
input   layer12_out_full_n;
output   layer12_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer9_out_read;
reg layer12_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    y0_input_TDATA_blk_n;
wire    ap_CS_fsm_state6;
reg    layer12_out_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [15:0] out_data_q1;
reg   [15:0] out_data_load_reg_1253;
wire   [15:0] out_data_1_q1;
reg   [15:0] out_data_1_load_reg_1258;
wire   [15:0] out_data_2_q1;
reg   [15:0] out_data_2_load_reg_1263;
wire   [15:0] out_data_3_q1;
reg   [15:0] out_data_3_load_reg_1268;
wire   [15:0] out_data_4_q1;
reg   [15:0] out_data_4_load_reg_1273;
wire   [15:0] out_data_5_q1;
reg   [15:0] out_data_5_load_reg_1278;
wire   [15:0] out_data_6_q1;
reg   [15:0] out_data_6_load_reg_1283;
wire   [15:0] out_data_7_q1;
reg   [15:0] out_data_7_load_reg_1288;
wire   [15:0] out_data_8_q1;
reg   [15:0] out_data_8_load_reg_1293;
wire   [15:0] out_data_9_q1;
reg   [15:0] out_data_9_load_reg_1298;
wire   [15:0] out_data_10_q1;
reg   [15:0] out_data_10_load_reg_1303;
wire   [15:0] out_data_11_q1;
reg   [15:0] out_data_11_load_reg_1308;
wire   [15:0] out_data_12_q1;
reg   [15:0] out_data_12_load_reg_1313;
wire   [15:0] out_data_q0;
reg   [15:0] out_data_load_1_reg_1318;
wire   [15:0] out_data_1_q0;
reg   [15:0] out_data_1_load_1_reg_1323;
wire   [15:0] out_data_2_q0;
reg   [15:0] out_data_2_load_1_reg_1328;
wire   [15:0] out_data_3_q0;
reg   [15:0] out_data_3_load_1_reg_1333;
wire   [15:0] out_data_4_q0;
reg   [15:0] out_data_4_load_1_reg_1338;
wire   [15:0] out_data_5_q0;
reg   [15:0] out_data_5_load_1_reg_1343;
wire   [15:0] out_data_6_q0;
reg   [15:0] out_data_6_load_1_reg_1348;
wire   [15:0] out_data_7_q0;
reg   [15:0] out_data_7_load_1_reg_1353;
wire   [15:0] out_data_8_q0;
reg   [15:0] out_data_8_load_1_reg_1358;
wire   [15:0] out_data_9_q0;
reg   [15:0] out_data_9_load_1_reg_1363;
wire   [15:0] out_data_10_q0;
reg   [15:0] out_data_10_load_1_reg_1368;
wire   [15:0] out_data_11_q0;
reg   [15:0] out_data_11_load_1_reg_1373;
wire   [15:0] out_data_12_q0;
reg   [15:0] out_data_12_load_1_reg_1378;
wire    ap_CS_fsm_state5;
reg   [15:0] out_data_load_2_reg_1513;
reg   [15:0] out_data_1_load_2_reg_1518;
reg   [15:0] out_data_2_load_2_reg_1523;
reg   [15:0] out_data_3_load_2_reg_1528;
reg   [15:0] out_data_4_load_2_reg_1533;
reg   [15:0] out_data_5_load_2_reg_1538;
reg   [15:0] out_data_6_load_2_reg_1543;
reg   [15:0] out_data_7_load_2_reg_1548;
reg   [15:0] out_data_8_load_2_reg_1553;
reg   [15:0] out_data_9_load_2_reg_1558;
reg   [15:0] out_data_10_load_2_reg_1563;
reg   [15:0] out_data_11_load_2_reg_1568;
reg   [15:0] out_data_12_load_2_reg_1573;
reg   [15:0] out_data_load_3_reg_1578;
reg   [15:0] out_data_1_load_3_reg_1583;
reg   [15:0] out_data_2_load_3_reg_1588;
reg   [15:0] out_data_3_load_3_reg_1593;
reg   [15:0] out_data_4_load_3_reg_1598;
reg   [15:0] out_data_5_load_3_reg_1603;
reg   [15:0] out_data_6_load_3_reg_1608;
reg   [15:0] out_data_7_load_3_reg_1613;
reg   [15:0] out_data_8_load_3_reg_1618;
reg   [15:0] out_data_9_load_3_reg_1623;
reg   [15:0] out_data_10_load_3_reg_1628;
reg   [15:0] out_data_11_load_3_reg_1633;
reg   [15:0] out_data_12_load_3_reg_1638;
reg   [2:0] out_data_address0;
reg    out_data_ce0;
reg    out_data_we0;
reg   [2:0] out_data_address1;
reg    out_data_ce1;
reg   [2:0] out_data_1_address0;
reg    out_data_1_ce0;
reg    out_data_1_we0;
reg   [2:0] out_data_1_address1;
reg    out_data_1_ce1;
reg   [2:0] out_data_2_address0;
reg    out_data_2_ce0;
reg    out_data_2_we0;
reg   [2:0] out_data_2_address1;
reg    out_data_2_ce1;
reg   [2:0] out_data_3_address0;
reg    out_data_3_ce0;
reg    out_data_3_we0;
reg   [2:0] out_data_3_address1;
reg    out_data_3_ce1;
reg   [2:0] out_data_4_address0;
reg    out_data_4_ce0;
reg    out_data_4_we0;
reg   [2:0] out_data_4_address1;
reg    out_data_4_ce1;
reg   [2:0] out_data_5_address0;
reg    out_data_5_ce0;
reg    out_data_5_we0;
reg   [2:0] out_data_5_address1;
reg    out_data_5_ce1;
reg   [2:0] out_data_6_address0;
reg    out_data_6_ce0;
reg    out_data_6_we0;
reg   [2:0] out_data_6_address1;
reg    out_data_6_ce1;
reg   [2:0] out_data_7_address0;
reg    out_data_7_ce0;
reg    out_data_7_we0;
reg   [2:0] out_data_7_address1;
reg    out_data_7_ce1;
reg   [2:0] out_data_8_address0;
reg    out_data_8_ce0;
reg    out_data_8_we0;
reg   [2:0] out_data_8_address1;
reg    out_data_8_ce1;
reg   [2:0] out_data_9_address0;
reg    out_data_9_ce0;
reg    out_data_9_we0;
reg   [2:0] out_data_9_address1;
reg    out_data_9_ce1;
reg   [2:0] out_data_10_address0;
reg    out_data_10_ce0;
reg    out_data_10_we0;
reg   [2:0] out_data_10_address1;
reg    out_data_10_ce1;
reg   [2:0] out_data_11_address0;
reg    out_data_11_ce0;
reg    out_data_11_we0;
reg   [2:0] out_data_11_address1;
reg    out_data_11_ce1;
reg   [2:0] out_data_12_address0;
reg    out_data_12_ce0;
reg    out_data_12_we0;
reg   [2:0] out_data_12_address1;
reg    out_data_12_ce1;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_done;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_idle;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_ready;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_layer9_out_read;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_d0;
wire   [2:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_address0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_ce0;
wire    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_we0;
wire   [15:0] grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_d0;
reg    grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg;
reg    ap_block_state1_ignore_call30;
wire    ap_CS_fsm_state2;
reg    ap_block_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_y0_input_U_apdone_blk;
wire   [15:0] y0_input_TDATA_int_regslice;
wire    y0_input_TVALID_int_regslice;
reg    y0_input_TREADY_int_regslice;
wire    regslice_both_y0_input_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg = 1'b0;
end

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_address0),
    .ce0(out_data_ce0),
    .we0(out_data_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_d0),
    .q0(out_data_q0),
    .address1(out_data_address1),
    .ce1(out_data_ce1),
    .q1(out_data_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_1_address0),
    .ce0(out_data_1_ce0),
    .we0(out_data_1_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_d0),
    .q0(out_data_1_q0),
    .address1(out_data_1_address1),
    .ce1(out_data_1_ce1),
    .q1(out_data_1_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_2_address0),
    .ce0(out_data_2_ce0),
    .we0(out_data_2_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_d0),
    .q0(out_data_2_q0),
    .address1(out_data_2_address1),
    .ce1(out_data_2_ce1),
    .q1(out_data_2_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_3_address0),
    .ce0(out_data_3_ce0),
    .we0(out_data_3_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_d0),
    .q0(out_data_3_q0),
    .address1(out_data_3_address1),
    .ce1(out_data_3_ce1),
    .q1(out_data_3_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_4_address0),
    .ce0(out_data_4_ce0),
    .we0(out_data_4_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_d0),
    .q0(out_data_4_q0),
    .address1(out_data_4_address1),
    .ce1(out_data_4_ce1),
    .q1(out_data_4_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_5_address0),
    .ce0(out_data_5_ce0),
    .we0(out_data_5_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_d0),
    .q0(out_data_5_q0),
    .address1(out_data_5_address1),
    .ce1(out_data_5_ce1),
    .q1(out_data_5_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_6_address0),
    .ce0(out_data_6_ce0),
    .we0(out_data_6_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_d0),
    .q0(out_data_6_q0),
    .address1(out_data_6_address1),
    .ce1(out_data_6_ce1),
    .q1(out_data_6_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_7_address0),
    .ce0(out_data_7_ce0),
    .we0(out_data_7_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_d0),
    .q0(out_data_7_q0),
    .address1(out_data_7_address1),
    .ce1(out_data_7_ce1),
    .q1(out_data_7_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_8_address0),
    .ce0(out_data_8_ce0),
    .we0(out_data_8_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_d0),
    .q0(out_data_8_q0),
    .address1(out_data_8_address1),
    .ce1(out_data_8_ce1),
    .q1(out_data_8_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_9_address0),
    .ce0(out_data_9_ce0),
    .we0(out_data_9_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_d0),
    .q0(out_data_9_q0),
    .address1(out_data_9_address1),
    .ce1(out_data_9_ce1),
    .q1(out_data_9_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_10_address0),
    .ce0(out_data_10_ce0),
    .we0(out_data_10_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_d0),
    .q0(out_data_10_q0),
    .address1(out_data_10_address1),
    .ce1(out_data_10_ce1),
    .q1(out_data_10_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_11_address0),
    .ce0(out_data_11_ce0),
    .we0(out_data_11_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_d0),
    .q0(out_data_11_q0),
    .address1(out_data_11_address1),
    .ce1(out_data_11_ce1),
    .q1(out_data_11_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s_out_data_ROgC #(
    .DataWidth( 16 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
out_data_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_data_12_address0),
    .ce0(out_data_12_ce0),
    .we0(out_data_12_we0),
    .d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_d0),
    .q0(out_data_12_q0),
    .address1(out_data_12_address1),
    .ce1(out_data_12_ce1),
    .q1(out_data_12_q1)
);

myproject_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1 grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start),
    .ap_done(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_done),
    .ap_idle(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_idle),
    .ap_ready(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_ready),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(4'd0),
    .layer9_out_fifo_cap(4'd0),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_layer9_out_read),
    .out_data_12_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_address0),
    .out_data_12_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_ce0),
    .out_data_12_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_we0),
    .out_data_12_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_d0),
    .out_data_11_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_address0),
    .out_data_11_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_ce0),
    .out_data_11_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_we0),
    .out_data_11_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_d0),
    .out_data_10_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_address0),
    .out_data_10_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_ce0),
    .out_data_10_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_we0),
    .out_data_10_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_d0),
    .out_data_9_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_address0),
    .out_data_9_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_ce0),
    .out_data_9_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_we0),
    .out_data_9_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_d0),
    .out_data_8_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_address0),
    .out_data_8_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_ce0),
    .out_data_8_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_we0),
    .out_data_8_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_d0),
    .out_data_7_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_address0),
    .out_data_7_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_ce0),
    .out_data_7_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_we0),
    .out_data_7_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_d0),
    .out_data_6_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_address0),
    .out_data_6_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_ce0),
    .out_data_6_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_we0),
    .out_data_6_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_d0),
    .out_data_5_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_address0),
    .out_data_5_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_ce0),
    .out_data_5_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_we0),
    .out_data_5_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_d0),
    .out_data_4_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_address0),
    .out_data_4_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_ce0),
    .out_data_4_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_we0),
    .out_data_4_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_d0),
    .out_data_3_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_address0),
    .out_data_3_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_ce0),
    .out_data_3_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_we0),
    .out_data_3_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_d0),
    .out_data_2_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_address0),
    .out_data_2_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_ce0),
    .out_data_2_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_we0),
    .out_data_2_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_d0),
    .out_data_1_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_address0),
    .out_data_1_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_ce0),
    .out_data_1_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_we0),
    .out_data_1_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_d0),
    .out_data_address0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_address0),
    .out_data_ce0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_ce0),
    .out_data_we0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_we0),
    .out_data_d0(grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_d0)
);

myproject_regslice_both #(
    .DataWidth( 16 ))
regslice_both_y0_input_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(y0_input_TDATA),
    .vld_in(y0_input_TVALID),
    .ack_in(regslice_both_y0_input_U_ack_in),
    .data_out(y0_input_TDATA_int_regslice),
    .vld_out(y0_input_TVALID_int_regslice),
    .ack_out(y0_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_y0_input_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg <= 1'b1;
        end else if ((grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_ready == 1'b1)) begin
            grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_10_load_1_reg_1368 <= out_data_10_q0;
        out_data_10_load_reg_1303 <= out_data_10_q1;
        out_data_11_load_1_reg_1373 <= out_data_11_q0;
        out_data_11_load_reg_1308 <= out_data_11_q1;
        out_data_12_load_1_reg_1378 <= out_data_12_q0;
        out_data_12_load_reg_1313 <= out_data_12_q1;
        out_data_1_load_1_reg_1323 <= out_data_1_q0;
        out_data_1_load_reg_1258 <= out_data_1_q1;
        out_data_2_load_1_reg_1328 <= out_data_2_q0;
        out_data_2_load_reg_1263 <= out_data_2_q1;
        out_data_3_load_1_reg_1333 <= out_data_3_q0;
        out_data_3_load_reg_1268 <= out_data_3_q1;
        out_data_4_load_1_reg_1338 <= out_data_4_q0;
        out_data_4_load_reg_1273 <= out_data_4_q1;
        out_data_5_load_1_reg_1343 <= out_data_5_q0;
        out_data_5_load_reg_1278 <= out_data_5_q1;
        out_data_6_load_1_reg_1348 <= out_data_6_q0;
        out_data_6_load_reg_1283 <= out_data_6_q1;
        out_data_7_load_1_reg_1353 <= out_data_7_q0;
        out_data_7_load_reg_1288 <= out_data_7_q1;
        out_data_8_load_1_reg_1358 <= out_data_8_q0;
        out_data_8_load_reg_1293 <= out_data_8_q1;
        out_data_9_load_1_reg_1363 <= out_data_9_q0;
        out_data_9_load_reg_1298 <= out_data_9_q1;
        out_data_load_1_reg_1318 <= out_data_q0;
        out_data_load_reg_1253 <= out_data_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_10_load_2_reg_1563 <= out_data_10_q1;
        out_data_10_load_3_reg_1628 <= out_data_10_q0;
        out_data_11_load_2_reg_1568 <= out_data_11_q1;
        out_data_11_load_3_reg_1633 <= out_data_11_q0;
        out_data_12_load_2_reg_1573 <= out_data_12_q1;
        out_data_12_load_3_reg_1638 <= out_data_12_q0;
        out_data_1_load_2_reg_1518 <= out_data_1_q1;
        out_data_1_load_3_reg_1583 <= out_data_1_q0;
        out_data_2_load_2_reg_1523 <= out_data_2_q1;
        out_data_2_load_3_reg_1588 <= out_data_2_q0;
        out_data_3_load_2_reg_1528 <= out_data_3_q1;
        out_data_3_load_3_reg_1593 <= out_data_3_q0;
        out_data_4_load_2_reg_1533 <= out_data_4_q1;
        out_data_4_load_3_reg_1598 <= out_data_4_q0;
        out_data_5_load_2_reg_1538 <= out_data_5_q1;
        out_data_5_load_3_reg_1603 <= out_data_5_q0;
        out_data_6_load_2_reg_1543 <= out_data_6_q1;
        out_data_6_load_3_reg_1608 <= out_data_6_q0;
        out_data_7_load_2_reg_1548 <= out_data_7_q1;
        out_data_7_load_3_reg_1613 <= out_data_7_q0;
        out_data_8_load_2_reg_1553 <= out_data_8_q1;
        out_data_8_load_3_reg_1618 <= out_data_8_q0;
        out_data_9_load_2_reg_1558 <= out_data_9_q1;
        out_data_9_load_3_reg_1623 <= out_data_9_q0;
        out_data_load_2_reg_1513 <= out_data_q1;
        out_data_load_3_reg_1578 <= out_data_q0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        layer12_out_write = 1'b1;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer9_out_read = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_layer9_out_read;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_10_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_10_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_10_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_10_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_address0;
    end else begin
        out_data_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_10_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_10_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_10_address1 = 64'd0;
    end else begin
        out_data_10_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_10_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_10_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_ce0;
    end else begin
        out_data_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_10_ce1 = 1'b1;
    end else begin
        out_data_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_10_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_10_we0;
    end else begin
        out_data_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_11_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_11_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_11_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_11_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_address0;
    end else begin
        out_data_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_11_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_11_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_11_address1 = 64'd0;
    end else begin
        out_data_11_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_11_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_11_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_ce0;
    end else begin
        out_data_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_11_ce1 = 1'b1;
    end else begin
        out_data_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_11_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_11_we0;
    end else begin
        out_data_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_12_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_12_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_12_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_12_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_address0;
    end else begin
        out_data_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_12_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_12_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_12_address1 = 64'd0;
    end else begin
        out_data_12_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_12_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_12_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_ce0;
    end else begin
        out_data_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_12_ce1 = 1'b1;
    end else begin
        out_data_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_12_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_12_we0;
    end else begin
        out_data_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_1_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_1_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_address0;
    end else begin
        out_data_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_1_address1 = 64'd0;
    end else begin
        out_data_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_1_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_ce0;
    end else begin
        out_data_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_1_ce1 = 1'b1;
    end else begin
        out_data_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_1_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_1_we0;
    end else begin
        out_data_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_2_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_2_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_2_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_address0;
    end else begin
        out_data_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_2_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_2_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_2_address1 = 64'd0;
    end else begin
        out_data_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_2_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_ce0;
    end else begin
        out_data_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_2_ce1 = 1'b1;
    end else begin
        out_data_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_2_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_2_we0;
    end else begin
        out_data_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_3_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_3_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_3_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_address0;
    end else begin
        out_data_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_3_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_3_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_3_address1 = 64'd0;
    end else begin
        out_data_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_3_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_ce0;
    end else begin
        out_data_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_3_ce1 = 1'b1;
    end else begin
        out_data_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_3_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_3_we0;
    end else begin
        out_data_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_4_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_4_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_4_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_4_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_address0;
    end else begin
        out_data_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_4_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_4_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_4_address1 = 64'd0;
    end else begin
        out_data_4_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_4_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_ce0;
    end else begin
        out_data_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_4_ce1 = 1'b1;
    end else begin
        out_data_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_4_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_4_we0;
    end else begin
        out_data_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_5_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_5_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_5_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_5_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_address0;
    end else begin
        out_data_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_5_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_5_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_5_address1 = 64'd0;
    end else begin
        out_data_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_5_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_ce0;
    end else begin
        out_data_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_5_ce1 = 1'b1;
    end else begin
        out_data_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_5_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_5_we0;
    end else begin
        out_data_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_6_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_6_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_6_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_6_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_address0;
    end else begin
        out_data_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_6_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_6_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_6_address1 = 64'd0;
    end else begin
        out_data_6_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_6_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_ce0;
    end else begin
        out_data_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_6_ce1 = 1'b1;
    end else begin
        out_data_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_6_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_6_we0;
    end else begin
        out_data_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_7_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_7_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_7_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_7_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_address0;
    end else begin
        out_data_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_7_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_7_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_7_address1 = 64'd0;
    end else begin
        out_data_7_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_7_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_ce0;
    end else begin
        out_data_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_7_ce1 = 1'b1;
    end else begin
        out_data_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_7_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_7_we0;
    end else begin
        out_data_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_8_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_8_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_8_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_8_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_address0;
    end else begin
        out_data_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_8_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_8_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_8_address1 = 64'd0;
    end else begin
        out_data_8_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_8_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_8_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_ce0;
    end else begin
        out_data_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_8_ce1 = 1'b1;
    end else begin
        out_data_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_8_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_8_we0;
    end else begin
        out_data_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_9_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_9_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_9_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_9_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_address0;
    end else begin
        out_data_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_9_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_9_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_9_address1 = 64'd0;
    end else begin
        out_data_9_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_9_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_9_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_ce0;
    end else begin
        out_data_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_9_ce1 = 1'b1;
    end else begin
        out_data_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_9_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_9_we0;
    end else begin
        out_data_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_address0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_address0;
    end else begin
        out_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_data_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_data_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        out_data_address1 = 64'd0;
    end else begin
        out_data_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_ce0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_ce0;
    end else begin
        out_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_data_ce1 = 1'b1;
    end else begin
        out_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_data_we0 = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_out_data_we0;
    end else begin
        out_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y0_input_TDATA_blk_n = y0_input_TVALID_int_regslice;
    end else begin
        y0_input_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        y0_input_TREADY_int_regslice = 1'b1;
    end else begin
        y0_input_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if ((~((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call30 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((y0_input_TVALID_int_regslice == 1'b0) | (layer12_out_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start = grp_concatenate1d_array_array_array_ap_fixed_79u_config12_Pipeline_ConcatLoop1_fu_850_ap_start_reg;

assign layer12_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{y0_input_TDATA_int_regslice}, {out_data_12_q0}}, {out_data_11_q0}}, {out_data_10_q0}}, {out_data_9_q0}}, {out_data_8_q0}}, {out_data_7_q0}}, {out_data_6_q0}}, {out_data_5_q0}}, {out_data_4_q0}}, {out_data_3_q0}}, {out_data_2_q0}}, {out_data_1_q0}}, {out_data_q0}}, {out_data_12_q1}}, {out_data_11_q1}}, {out_data_10_q1}}, {out_data_9_q1}}, {out_data_8_q1}}, {out_data_7_q1}}, {out_data_6_q1}}, {out_data_5_q1}}, {out_data_4_q1}}, {out_data_3_q1}}, {out_data_2_q1}}, {out_data_1_q1}}, {out_data_q1}}, {out_data_12_load_3_reg_1638}}, {out_data_11_load_3_reg_1633}}, {out_data_10_load_3_reg_1628}}, {out_data_9_load_3_reg_1623}}, {out_data_8_load_3_reg_1618}}, {out_data_7_load_3_reg_1613}}, {out_data_6_load_3_reg_1608}}, {out_data_5_load_3_reg_1603}}, {out_data_4_load_3_reg_1598}}, {out_data_3_load_3_reg_1593}}, {out_data_2_load_3_reg_1588}}, {out_data_1_load_3_reg_1583}}, {out_data_load_3_reg_1578}}, {out_data_12_load_2_reg_1573}}, {out_data_11_load_2_reg_1568}}, 
    {out_data_10_load_2_reg_1563}}, {out_data_9_load_2_reg_1558}}, {out_data_8_load_2_reg_1553}}, {out_data_7_load_2_reg_1548}}, {out_data_6_load_2_reg_1543}}, {out_data_5_load_2_reg_1538}}, {out_data_4_load_2_reg_1533}}, {out_data_3_load_2_reg_1528}}, {out_data_2_load_2_reg_1523}}, {out_data_1_load_2_reg_1518}}, {out_data_load_2_reg_1513}}, {out_data_12_load_1_reg_1378}}, {out_data_11_load_1_reg_1373}}, {out_data_10_load_1_reg_1368}}, {out_data_9_load_1_reg_1363}}, {out_data_8_load_1_reg_1358}}, {out_data_7_load_1_reg_1353}}, {out_data_6_load_1_reg_1348}}, {out_data_5_load_1_reg_1343}}, {out_data_4_load_1_reg_1338}}, {out_data_3_load_1_reg_1333}}, {out_data_2_load_1_reg_1328}}, {out_data_1_load_1_reg_1323}}, {out_data_load_1_reg_1318}}, {out_data_12_load_reg_1313}}, {out_data_11_load_reg_1308}}, {out_data_10_load_reg_1303}}, {out_data_9_load_reg_1298}}, {out_data_8_load_reg_1293}}, {out_data_7_load_reg_1288}}, {out_data_6_load_reg_1283}}, {out_data_5_load_reg_1278}}, {out_data_4_load_reg_1273}}, {out_data_3_load_reg_1268}}, 
    {out_data_2_load_reg_1263}}, {out_data_1_load_reg_1258}}, {out_data_load_reg_1253}};

assign start_out = real_start;

assign y0_input_TREADY = regslice_both_y0_input_U_ack_in;

endmodule //myproject_concatenate1d_array_array_array_ap_fixed_16_6_5_3_0_79u_config12_s
